### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by RobertoJBeltran** [soppongamoateng/typing-game#2]
Hey Sam,

I really like your typing game. I understand you want everyone to use and modify your game freely. You should add a license so people know that is your intention. It can be as simple as adding MIT license.

**Comment by samamoateng** [comment]
Thanks for the feedback I will add a license to the repository. I am got up
with looking for a remote job at the moment so I barely get time.

I have plans on working on a newer version when I get the time. Thanks agn

**Comment by samamoateng** [comment]
I have added a license to the repository
